
services:
  frontend:
    image: frontend
    build:
      context: ./nodejs/frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - outer
      - inner

  backend:
    image: backend
    build:
      context: ./nodejs/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      DB_URI: mongodb://mongodb:27017/dbrs
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    networks:
      - inner
      - outer #TODO: Remove

  # first service to start
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: mymongo
    #command to be executed after execution initialized
    command: [ "docker-entrypoint.sh", "mongod" ]
    restart: always
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s
    networks:
      - inner

  #TODO: Comment out because only used for debug reasons
  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/dbrs
    restart: always
    ports:
      - "8082:8081"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    networks:
      - inner
      - outer

networks:
  inner:
    driver: bridge
    internal: true
    driver_opts:
       com.docker.network.bridge.name: "br-inner89012"
       com.docker.network.enable_ipv6: "false"
  outer:
    driver: bridge
    internal: false
    driver_opts:
       com.docker.network.bridge.name: "br-outer89012"
       com.docker.network.enable_ipv6: "false"