
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - inner

  frontend:
    image: frontend
    build:
      context: ./nodejs/frontend
      dockerfile: Dockerfile
    volumes: #Aggiunto per permettere modifiche live alla view
      - ./nodejs/frontend:/app
      - /app/node_modules  # Previene conflitti tra node_modules host e container
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    ports:
      - 5173:5173
    depends_on:
      - proxy
    networks:
      - outer
      - inner

  backend1:
    build:
      context: ./nodejs/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      DB_URI: mongodb://mongodb:27017,mongo-secondary:27017/dbrs?replicaSet=rs0&readPreference=primaryPreferred
      SEED_DATABASE: "true"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - mongodb
      - redis
    networks:
      - inner

  backend2:
    build:
      context: ./nodejs/backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      DB_URI: mongodb://mongodb:27017,mongo-secondary:27017/dbrs?replicaSet=rs0&readPreference=primaryPreferred
      SEED_DATABASE: "false"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - mongodb
      - redis
    networks:
      - inner
  
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: mymongo
    command: [ "mongod", "--replSet", "rs0" ]
    restart: always
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongosh --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - inner

  mongo-secondary:
    image: mymongo
    command: [ "mongod", "--replSet", "rs0" ]
    restart: always
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongosh --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - inner

  mongo-arbiter:
    image: mymongo
    container_name: mongo-arbiter
    networks:
      - inner
    command: mongod --replSet rs0 --port 27017 --bind_ip_all


  mongo-init:
    image: mymongo
    depends_on:
      - mongodb
      - mongo-secondary
    volumes:
      - ./mongodb/init-replica.sh:/init-replica.sh
    entrypoint: [ "bash", "/init-replica.sh" ]
    networks:
      - inner


  #TODO: Comment out because only used for debug reasons
  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/dbrs
    restart: always
    ports:
      - "8082:8081"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    networks:
      - inner
      - outer

  proxy:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - inner
      - outer


networks:
  inner:
    driver: bridge
    internal: false #Impostato a false poichè i backend necessitano di accedere ad internet per le chiamate API
    driver_opts:
       com.docker.network.bridge.name: "br-inner89012"
       com.docker.network.enable_ipv6: "false"
  outer:
    driver: bridge
    internal: false
    driver_opts:
       com.docker.network.bridge.name: "br-outer89012"
       com.docker.network.enable_ipv6: "false"